### ISSUE TITLE
Epic - Managing State Transitions

### ISSUE THREAD

**Issue by Buwujiu** [Pan-Canadian-Genome-Library/daco#3]
## Descriptions
Build a service layer to manage application state transitions. 
This is an epic for all state transition actions.

All states are in the diagram below:
https://drive.google.com/file/d/1BjtTpNjSG-GZ16cRhNxVMO66Nb-orq8A/view?usp=sharing
or 
https://docs.google.com/drawings/d/1CI-nB8MBr6Abc6DlGCr2moKNFcfHaG_YjRU1uVk61Lw/edit?usp=sharing

Dependency on ticket #6 . 

## Tasks
For the first task, must:
1. set finite state model, choose a library - DONE
2. add all state transition actions - DONE
**3. implement the DB persistence layer, Jon and Dan to add details**

All tasks are broken down by actions and paths:

- [x] Ticket 1: https://github.com/Pan-Canadian-Genome-Library/daco/issues/58
- [x] Ticket 2: https://github.com/Pan-Canadian-Genome-Library/daco/issues/59
- [x] Ticket 3: https://github.com/Pan-Canadian-Genome-Library/daco/issues/60
- [x] Ticket 4: https://github.com/Pan-Canadian-Genome-Library/daco/issues/61
- [x] Ticket 5: https://github.com/Pan-Canadian-Genome-Library/daco/issues/62
- [ ] Ticket 6: https://github.com/Pan-Canadian-Genome-Library/daco/issues/63

## All Actions:
1. Submit draft application, todo: send emails to related users.
2. Rep approves 
3. Rep requests revisions
4. Applicant submits Rep revisions
5. DAC approves
6. DAC rejects
7. DAC requests revisions
8. Applicant submits DAC revisions
9. DAC revokes
10. Applicant closes applications
11. Applicant withdraws

**Comment by Buwujiu** [comment]
Dan and Jon will meet to discuss the tasks. Will need APIs and code mechanism.

**Comment by Buwujiu** [comment]
All sub-issues are completed in this PR: https://github.com/Pan-Canadian-Genome-Library/daco/pull/86. Closing epic.

**Comment by Buwujiu** [comment]
Missing the state transition DB updates, Dan and Jon to identify missing parts.

**Comment by demariadaniel** [comment]
PR #153 covers Issues #59, #60  & #61 
There is testing code connecting the 'happy path' and the 'revision' transitions so I updated them all together
There are still a few transitions related to 'close'/'revoke'/'withdraw' etc which can be completed separately once this PR is signed off + merged and any changes are addressed

**Comment by Buwujiu** [comment]
All tickets are merged, closing.
