### ISSUE TITLE
DACO Rest API

### ISSUE THREAD

**Issue by Buwujiu** [Pan-Canadian-Genome-Library/daco#44]
All REST endpoints: 

- [x] - list applications https://github.com/Pan-Canadian-Genome-Library/daco/issues/64
- [x] - get application by ID https://github.com/Pan-Canadian-Genome-Library/daco/issues/85
- [x] - get user info - email and name - from user session https://github.com/Pan-Canadian-Genome-Library/daco/issues/114
- [x] - Create application https://github.com/Pan-Canadian-Genome-Library/daco/issues/84
- [x] - update content, save application https://github.com/Pan-Canadian-Genome-Library/daco/issues/112
- [x] - Submit Application https://github.com/Pan-Canadian-Genome-Library/daco/issues/115
- [ ] - Rep request revisions application https://github.com/Pan-Canadian-Genome-Library/daco/issues/116
- [ ] - DAC approve https://github.com/Pan-Canadian-Genome-Library/daco/issues/117
- [ ] - DAC request revisions https://github.com/Pan-Canadian-Genome-Library/daco/issues/118
- [ ] - DAC reject https://github.com/Pan-Canadian-Genome-Library/daco/issues/119
- [ ] - Applicant submits revisions https://github.com/Pan-Canadian-Genome-Library/daco/issues/120
- [ ] - Applicant closes application https://github.com/Pan-Canadian-Genome-Library/daco/issues/121
- [x] - DAC closes application https://github.com/Pan-Canadian-Genome-Library/daco/issues/122
- [ ] - Applicant and DAC revoke application https://github.com/Pan-Canadian-Genome-Library/daco/issues/123
- [x] - Get/Edit/Delete/Add/Update collaborators https://github.com/Pan-Canadian-Genome-Library/daco/issues/124

**Comment by demariadaniel** [comment]
Includes Swagger + Logging Set Up
