### ISSUE TITLE
Support French

### ISSUE THREAD

**Issue by Buwujiu** [Pan-Canadian-Genome-Library/daco#70]
## Requirement
 - [ ] We will add French translation text to make DACO fully French. 
- [ ] Emails & PDF also needs to be in French. 
- [ ] todo: ask Ma'n - PDF: does generated PDF have to be in French as well? is it ok to have pdfs in both languages? 
- [ ] We will need to resize UI depending on French text. 
- [ ] For emails, we will show both English and French by default. This is easier to implement, without having to pick up user's language choice. 

## Estimate
Estimates for the remaining tasks for building lanaguage toggle, adding french text, adding french to emails, testing layout: 5 - 7 days.

**Comment by surajgoraya** [comment]
Leaving this here for reference :) 

We had a lengthy-ish discussion regarding behaviour for when this implemented post-MVP in #111. - See: https://github.com/Pan-Canadian-Genome-Library/daco/pull/111#discussion_r1888821678

**Comment by Buwujiu** [comment]
Will invite French speaking users from Mcgill to test the translation, closing ticket.
