### ISSUE TITLE
Implement DACO i18n

### ISSUE THREAD

**Issue by JamesTLopez** [Pan-Canadian-Genome-Library/daco#94]
## Description 

Going forward into development, we want to start apply translations to the text in the app.
Integrate internationalization into app using the library [i18next](https://www.i18next.com/)

## Tasks

- [x] Setup i18next to be usable across the app
- [x] Create translation files:
    - [x] English
    - [x] French
- [x] Replace text on:
    - [x] Homepage
    - [x] Dashboard
- <s>[x] Implement language switch with url</s>
    - [x] <s>Ex:`www.{domain}.com/fr/*`. should convert the webpage into french</s>
    - [x] <s>Ex:`www.{domain}.com/en/*`. should convert the webpage into french</s>
    - [x] <s>Anything not specified will default into english</s>
- [x] retire date formatter logic in utils and use intl.api to formate that dates instead

**Comment by JamesTLopez** [comment]
NOTE: language switch will be implemented POST-MVP. This ticket is to setup the foundation. [Relevant](https://github.com/orgs/Pan-Canadian-Genome-Library/projects/1/views/1?pane=issue&itemId=88042895&issue=Pan-Canadian-Genome-Library%7Cdaco%7C70)
